# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# -------------------------------

# by running this file YOU WILL LOSE any previously created Items, Carts

Story.destroy_all # !!!!!!!

story1 = Story.create(date: "2020-12-26", transcriber: "Lindsay", contributor: "Thomas J", contact_email: "thomas@me.com", contact_phone: "917-801-9475", summary: "Morbi faucibus ferm entum quam, setit.", story: "Lorem ipsum dolor sit amet, hinc numquam patrioque nam ad. Ad ubique putent delicatissimi est, iuvaret dignissim persecuti ius ea, vim bonorum debitis no. Assum possim albucius vix te, cu electram iracundia sea. Eu ius labores vivendo insolens, eum et docendi percipit ullamcorper. Nam no saperet laoreet ancillae, has saepe saperet id, lorem postea evertitur sit cu. Justo quando sit ne, menandri repudiare ea est, at minimum constituam cotidieque pri. An tempor aperiri nostrum eam. Zril accommodare quo no, pri equidem suavitate persequeris ut, eu adolescens omittantur consectetuer mea. Et nam sapientem ocurreret, ius elit inciderint in. Duo at prima democritum, pri movet detracto conceptam ne. No sanctus democritum mea, nec ea choro blandit volutpat, vim justo graeci salutandi ad. Mei id exerci aliquid, sit in elitr tritani percipitur. Ex sit movet accumsan deleniti. Probo vituperata instructior ius at. Mel mutat inimicus ei. Ea per euripidis definiebas. Eos iusto maiestatis te. Option gloriatur ea vis, cu nostro argumentum eos, an similique appellantur vel. Nec iriure epicuri moderatius an, mea ex cibo primis argumentum. Ne sit facer audiam interesset, at putant epicuri nam. Mel at regione scribentur, ne unum appellantur eam. Nibh everti ullamcorper eum ad. No vis graeco epicurei interpretaris, sed graeco causae discere at. Per stet everti verear ex, postea mandamus ullamcorper no duo. At usu tantas nostrum, ad vitae timeam eam.", image:"https://res.cloudinary.com/djsz02nwd/image/upload/v1609003407/20181020_IRP003_0_mpri0p.jpg" )
story2 = Story.create(date: "2020-12-28", transcriber: "Jaime", contributor: "Sylvia P", contact_email: "sylvia@me.com", contact_phone: "803-465-9860", summary: "Tinci sollicitudin luctus. Maece.", story: "Mel ea modo utinam convenire, doming appareat ex vix, at sed omnium fierent delectus. Cu quem scripserit pri, te ubique graeci mei. His wisi aliquip prodesset ne, an vel movet nihil doctus, eu vis dolor facilisis. Qui prima nonumy te, dico vero an eum, fugit deseruisse cu vis. Mel ornatus deserunt id, ex latine convenire usu. At soleat mentitum pri, nibh dolores liberavisse ut ius. Ea mel paulo doming reprimique, vix ne recteque sententiae. Eos quis sumo constituam ei, malis scribentur cu vis. Ea eius debitis qui, sea cu libris consetetur. Ex tibique accommodare pro, qui cu tritani tibique elaboraret. Ancillae pertinacia id mei, meis elitr ullamcorper has an. Vel graece iriure laboramus ad, efficiantur suscipiantur duo id. Ea dicant patrioque mei. Id inermis deserunt signiferumque eam, in per iusto tempor vituperata. Mel melius prodesset signiferumque te, ut mel primis aliquam consequuntur, mucius ancillae sea et. Unum fugit has id, his alia debitis nominati cu. Ad illud mediocrem patrioque has, vim te dicat vituperatoribus, utroque repudiare interesset nec et. Usu no wisi delenit, per eu alterum molestiae instructior. Iudico nominati consetetur te pro, qui te eros dolorum, putent nostrud adolescens sea eu. Cum te noster epicurei volutpat, his id harum eloquentiam, te eam etiam aeterno reformidans. Has omnis erant doming ex. Mel legere omnesque insolens in. Ludus labores eam in, modo libris noluisse sit cu. Vel mutat iuvaret consectetuer ei, ne graecis nostrum interpretaris eum. Nihil nusquam interpretaris ex eum, falli mundi mentitum est ad, dicam habemus democritum an duo. Nam putant adipiscing ex, iuvaret patrioque efficiantur quo ex, ad dolorem accusam vis. Vivendum platonem efficiendi quo ne. Mel harum voluptatibus ut, ne vix ceteros delicata, an vix facilisi temporibus. Et nec civibus qualisque efficiendi, odio mazim oblique ei cum. Quo an amet noster antiopam, te homero mentitum eum. Eam illud mediocrem persequeris no, vel eu alterum nonumes inciderint, eam an bonorum consetetur comprehensam. Efficiendi accommodare no usu. Aliquid explicari id vim. Eum corpora invidunt referrentur ei. Pro nihil latine cotidieque at, per ad aeterno viderer persius. Est ex noluisse moderatius.", image:"https://res.cloudinary.com/djsz02nwd/image/upload/v1609003373/wonderlane-w1s5H_3Zn48-unsplash_opa6rm.jpg" )
story3 = Story.create(date: "2020-12-27", transcriber: "Lonna", contributor: "Marcus D", contact_email: "marcus@me.com", contact_phone: "954-657-4523", summary: "Elementum arcu felis, vel abrisus.", story: "Et per brute splendide, mei facilisis patrioque ad, ex tritani adipisci cum. Errem intellegebat disputationi ut has, eu sed insolens vituperatoribus. Eius molestiae an vel, labore scripta sed id, ne epicuri scripserit comprehensam his. Suscipit temporibus conclusionemque eum ne, ex eos dolorum prodesset. Salutandi iracundia an pri, et sit appareat honestatis, vix purto modus dolor ei. Vis ne vocent animal voluptatum. Vocibus constituam concludaturque vis ne, in duo invenire elaboraret dissentiunt, et solum reformidans vel.

Eu eam alia forensibus. No iriure appellantur pro, an graecis nusquam sed, doming lobortis sit eu. Qualisque definiebas eum ne, ad regione tritani reprehendunt vix. Ea est mentitum omnesque periculis. Eum exerci appareat ea, pri alii dicit deleniti eu, vim verear iudicabit eu. Qui eu principes tincidunt omittantur.

Ex sed bonorum vulputate, his ei omnis iriure minimum. Eu vel altera recusabo, nec meis philosophia et, sit delectus singulis te. Usu suas senserit no, usu cu elit sententiae, ius cu postea rationibus necessitatibus. Eum ei quando dicunt necessitatibus, sea te sale solum. Duo an doming minimum, no ius utinam theophrastus. Nulla dolores cu his. Amet partem everti ei vim, ex tale voluptua sit, affert aliquip iuvaret sit ut.

Ipsum exerci adipisci ei sea. Prima omnium albucius nec no, ad vis ignota mandamus splendide, ex dignissim instructior duo. Per an doctus rationibus. In ius iudico theophrastus, id eirmod aliquid salutandi has.

Evertitur temporibus eam ex, cu solum delicata repudiandae vis, nostro molestie perfecto ex mea. Quot idque nostrum est in. Qui alii phaedrum accusamus no, eum ut alterum conceptam. Cu vocibus legendos qui, te dictas docendi constituam has, latine forensibus ea usu. Eruditi graecis praesent ad per, ne errem adipisci qui.

Iudico offendit indoctum vim ad, stet latine ullamcorper cum ei. Quodsi corrumpit adipiscing vis cu, mea quas velit causae ad, eu mel mundi similique. Sea agam volutpat dissentiet et. Qui mediocrem ocurreret no, electram facilisis mei cu, est ea legere eleifend. Legere noster ei duo, ornatus offendit cu has.

Nec ut novum soleat consequuntur, primis malorum cu pro. An fastidii assueverit mei. Ne alienum legendos nec, id eos elit tantas. Lucilius deterruisset cum et. Id sit elit wisi voluptua.

Eu quod iriure saperet nec, eos id habeo ullum aeque, et probo prima nam. Sea integre intellegam cu. Sit luptatum patrioque ex, tation minimum eleifend ne qui. Eligendi prodesset ei eos, eu sed graeco iracundia, nec quod noster putant ea. Populo accusam vituperatoribus no vis, alterum deterruisset quo no. Quod magna ex est, everti perfecto mel ne.

Meis sonet postulant eam te, vis duis wisi persecuti cu. Nonumes reprimique pro at, eum eirmod integre te, ad veri illud alienum vim. Odio eruditi no qui, ea eum scripta vocibus evertitur, ei mei fugit eleifend referrentur. Sea ei diam persequeris. Eam in duis tantas.

An eam ceteros dolores pericula, duo ut facilisi pertinax. Est posse scriptorem philosophia ne. Nec veri mazim ea. At clita noluisse cum, vide efficiendi ea pro. Ea labore aperiri mea, cu etiam sadipscing sea. Vel ad debitis verterem, eu explicari intellegam persequeris vel.

Vidisse temporibus et eos. Vix et primis putent, veritus dignissim interesset at has. Id ius enim vivendum, pri at mollis principes reprimique. Justo expetendis vel te, deleniti deseruisse accommodare pro ex. Quo ceteros accusata ut, justo malis fierent vix cu, atqui nulla petentium usu ex. Cu ignota accumsan interpretaris cum, et eam sapientem salutatus.

Mandamus persequeris cu mea. Graece suscipiantur duo ea, mea albucius iudicabit dissentiunt ei. Eos semper epicurei verterem ea, est ut integre singulis. Vel erat dictas feugiat eu, mediocrem vituperata nam id.

No ius nisl libris. Eum cu neglegentur signiferumque, ne suscipiantur disputationi pro, cum no mediocrem concludaturque. Ea viris vivendo consectetuer eum, has doctus feugait commune ad. Ea altera iisque nam. Has an probatus mediocrem assentior, vim no altera vulputate.

Putent constituam ut his, graece alterum legendos ad quo, ne duo sumo liberavisse. No vix aliquam perpetua aliquando, eam odio graece ullamcorper in. Nibh iuvaret pri ad, sed ne tota fuisset blandit. Vis et altera habemus torquatos, et cetero tincidunt pri, eu ferri expetenda pro.

Alterum referrentur complectitur vel ei, etiam qualisque ex cum, sensibus pericula honestatis vis ad. Delenit reprimique at vis. Eum dico electram no, pro elit pericula salutandi ex, tempor denique electram nec ea. Usu tibique appetere apeirian ad, diam possit forensibus ea mei, putent voluptatibus eu vim.

Cu sed falli dictas abhorreant. His justo semper an, cu ludus melius perpetua vim. Unum tibique atomorum at eum, est justo inciderint id, te cum essent bonorum euripidis. Admodum electram eu sea.

Cu tantas dictas veritus usu, ea sed clita dignissim. Mei summo oportere et, eos nemore oporteat at. Erant possit deleniti vel id. Singulis temporibus eam ea, cu sed recteque hendrerit. Est adhuc detraxit id. Omnis laudem feugiat cum an, sed id vidit clita. Est ne latine laoreet appareat, ut qui altera sententiae, eirmod euismod vituperatoribus an mel.

Quot purto unum in ius, habeo eruditi vivendum duo ut, sit te nibh wisi honestatis. Ea usu oportere indoctum, no pro populo audire sapientem, ad audire aeterno nam. An sit graece debitis, docendi voluptatum pro eu. Delicata persequeris te nam, has splendide temporibus id. Delectus omittantur referrentur eu eam, amet ludus forensibus quo in, etiam eripuit pri at. Debitis recusabo pri ei, vim te splendide forensibus cotidieque, pri dolores verterem ex. Vel ex mundi dictas vituperatoribus.

Justo oporteat apeirian vix no. Munere animal vivendum ea pro. At feugiat inimicus usu. Viderer dissentiet ex pro, cum illum tollit laoreet ex. Illum nominavi id eam, sint tantas noster nam id. Ludus postulant aliquando eu est. Pro id detraxit postulant.

Hinc vivendum accusata pro an, vel iudicabit reprehendunt te. An unum tritani singulis qui. Ne epicurei pertinacia vituperata eum, sea at malis recusabo. Eam cu cetero luptatum theophrastus, duo doming facilisi recusabo ad, quot persius iuvaret vim cu. Cu vix eius suscipit patrioque. Has te sint harum conclusionemque, libris mollis officiis nam at.
", image:"https://res.cloudinary.com/djsz02nwd/image/upload/v1609003389/mike-von-G81cWMF7qhg-unsplash_vuxplb.jpg" )
